name: Lambda Deploy

on:
  push:
    branches:
      - main
      - develop
  pull_request_review:
    types: [submitted]

jobs:
  Build-Lambda:
    name: Build Lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          cd src/task_manager_lambda
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pytest
      